openapi: 3.0.4
info:
  title: Family Tree - OpenAPI 3.1
  version: 0.0.0
servers:
  - url: http://localhost:8080
paths:
  /person:
    post:
      description: Create person
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        '200':
          description: Successful create
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid payload
        default:
          description: Unexpected error
  /person/{dni}:
    get:
      description: Read person
      operationId: read
      parameters:
        - name: dni
          in: path
          description: ID of the person
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful read
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
        '404':
          description: Person not found
        default:
          description: Unexpected error
    put:
      description: Update person
      operationId: update
      parameters:
        - name: dni
          in: path
          description: ID of the person
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        '200':
          description: Successful update
        '404':
          description: Person not found
        default:
          description: Unexpected error
components:
  schemas:
    Person:
      type: object
      required:
        - dni
        - name
        - surname
      properties:
        dni:
          type: string
        name:
          type: string
        surname:
          type: string
        father:
          $ref: "#/components/schemas/Person"
        mother:
          $ref: "#/components/schemas/Person"
        brothers:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        sisters:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        husband:
          $ref: "#/components/schemas/Person"
        wife:
          $ref: "#/components/schemas/Person"
        children:
          type: array
          items:
            $ref: "#/components/schemas/Person"