POST http://localhost:8080/person
Accept: application/json
Content-Type: application/json

{
  "dni": "00000000A",
  "name": "Javier",
  "surname": "Celada"
}

###
@dni = 00000000A

###
GET http://localhost:8080/person/{{dni}}
Accept: application/json
Content-Type: application/json

###
PUT http://localhost:8080/person/{{dni}}
Content-Type: application/json

{
  "name": "Javier",
  "surname": "Celada"
}